### PR TITLE
working release

### PR DESCRIPTION
**Pull request by jethror1**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/cp_upload/1)

### CODE REVIEW

**Review by Addy81 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/cp_upload/1)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[dnanexus-upload-agent-1.5.32-linux.tar.gz, line 0 at r1](https://reviewable.io/reviews/eastgenomics/cp_upload/1#-MKLDDUF0MAGSZ_eJIin:-MKLDDUF0MAGSZ_eJIio:b3gwmji) ([raw file](https://github.com/eastgenomics/cp_upload/blob/818ae025642995ca0014aee98ebb1ced2a378b0f/dnanexus-upload-agent-1.5.32-linux.tar.gz#L0)):*
Should the tars be stored in the repo?
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/eastgenomics/cp_upload/1#-MKLCswSDWmX7cVbNFPC:-MKLCswSDWmX7cVbNFPD:boj5ooz) ([raw file](https://github.com/eastgenomics/cp_upload/blob/818ae025642995ca0014aee98ebb1ced2a378b0f/README.md#L2)):*
> ```Markdown
> # CP Upload
> Script to perform setup for uploading CP data to DNAnexus
> ```

Could we define CP once in this ReadMe?
___
*[README.md, line 17 at r1](https://reviewable.io/reviews/eastgenomics/cp_upload/1#-MKLD0-z8QvLbWI6paYy:-MKLD0-z8QvLbWI6paYz:b-j6w71d) ([raw file](https://github.com/eastgenomics/cp_upload/blob/818ae025642995ca0014aee98ebb1ced2a378b0f/README.md#L17)):*
> ```Markdown
> This requires the dnanexus_token.txt file to be added to the script directory.
> 
> ### This was made by EMEE GLH
> ```

Could you have one line showing how it is run?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/cp_upload/1)* status: all files reviewed, 3 unresolved discussions (waiting on @Addy81)

___
*[dnanexus-upload-agent-1.5.32-linux.tar.gz, line  at r1](https://reviewable.io/reviews/eastgenomics/cp_upload/1#-MKLDDUF0MAGSZ_eJIin:-MKZFR5Z1x8CWhe2_9mN:b2nign6) ([raw file](https://github.com/eastgenomics/cp_upload/blob/818ae025642995ca0014aee98ebb1ced2a378b0f/dnanexus-upload-agent-1.5.32-linux.tar.gz#L)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Should the tars be stored in the repo?
</blockquote></details>

yes
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/eastgenomics/cp_upload/1#-MKLCswSDWmX7cVbNFPC:-MKZGo8sDsv0PpNjzmuA:b-896fix) ([raw file](https://github.com/eastgenomics/cp_upload/blob/818ae025642995ca0014aee98ebb1ced2a378b0f/README.md#L2)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Could we define CP once in this ReadMe?
</blockquote></details>

Done.
___
*[README.md, line 17 at r1](https://reviewable.io/reviews/eastgenomics/cp_upload/1#-MKLD0-z8QvLbWI6paYy:-MKZGoXX3s7AaV4p63UO:b-896fix) ([raw file](https://github.com/eastgenomics/cp_upload/blob/818ae025642995ca0014aee98ebb1ced2a378b0f/README.md#L17)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Could you have one line showing how it is run?
</blockquote></details>

Done.

**Review by Addy81 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/cp_upload/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Addy81 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/cp_upload/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
